### ISSUE TITLE
Documentation inconsistancies

### ISSUE THREAD

**Issue by ConnorMac** [rehive/docs#23]
- [x] Transaction objects return an ‘id’ but filtering mentions a ‘tx_code’
- [x] https://docs.rehive.com/#create-mobile uses email instead of mobile
- [x] Certain docs still mention underscore urls ex. https://www.rehive.com/api/3/user/bitcoin_accounts/
- [x] https://docs.rehive.com/#resend-mobile-verification uses email instead of mobile
- [x] https://docs.rehive.com/#retrieve-profile and #update-profile response is incorrect
- [x] https://docs.rehive.com/#create-tier-limits mentions requirements in url

**Comment by OdinsPlasmaRifle** [comment]
Fixed
