### ISSUE TITLE
Global switches

### ISSUE THREAD

**Issue by crintus** [rehive/docs#25]
@AquiburRKhan has brought it to my attention that the GlobalSwitch documentation is somewhat misleading, which caused confusion as to why transactions were disabled. 

We need to rewrite it to make it more clear that the GlobalSwitch isn't the almighty switch but rather more of a "kill switch" We also need to reference or note that there are other switches which are nested in different sub categories.

**Comment by OdinsPlasmaRifle** [comment]
This is no longer relevant as switches were replaced by settings.
