### ISSUE TITLE
doc update

### ISSUE THREAD

**Issue by AquiburRKhan** [rehive/docs#31]
transaction webhook and user webhooks docs need to be updated

**Comment by OdinsPlasmaRifle** [comment]
This update has been completed, it just needs to be deployed.

**Comment by OdinsPlasmaRifle** [comment]
@AquiburRKhan this has been deployed. You can see the new transaction and user webhooks. In addition you can see the new "Beta Features" section: http://docs.rehive.com/#beta-features
