### ISSUE TITLE
Feature: Collapsable headers

### ISSUE THREAD

**Issue by Stephan-e** [rehive/docs#52]
It would be nice to have the header not only expand when clicking on it but if you click it again it would collapse, not making it necessary to scroll down to view another feature set.

**Comment by OdinsPlasmaRifle** [comment]
You are welcome to try your hand at this. We want to make the side navigation better. Something more like Stripe would make it easier to navigate as well: https://stripe.com/docs/api

**Comment by OdinsPlasmaRifle** [comment]
However, we also plan to separate the API docs into 2 parts: 

Admin API
User API

**Comment by Stephan-e** [comment]
Okay cool I'll take a crack at it.
I was already looking through the code :D

**Comment by Stephan-e** [comment]
Yoh, those stripe docs are nice.

**Comment by Stephan-e** [comment]
I think they used Slate. https://lord.github.io/slate/

**Comment by OdinsPlasmaRifle** [comment]
We can reconsider this in future designs of the docs. This is not something we want to spend time on in the current version.
