### ISSUE TITLE
Sidebar loads very slowly.

### ISSUE THREAD

**Issue by michailbrynard** [rehive/docs#55]

**Comment by OdinsPlasmaRifle** [comment]
Can't really do anything about this without rebuilding in a different tool.

**Comment by michailbrynard** [comment]
There's an issue in the slate repo itself about performance where the author suggests:
> Hey! I'm not sure about it, but it's conceivable that search is slowing it down. You should be able to disable search to compare the load speeds by setting search: false at the top of your index.html.md.

**Comment by michailbrynard** [comment]
He also says
> Stripe does some pretty crazy things to get their massive docs to load on a single page — unfortunately, we're unlikely to support those techniques, since they're way too complicated for this simple project. You could try breaking this up into more pages perhaps?
